#! /usr/bin/env python
import sys
import subprocess

parmfile = '/tmp/afrift_args'
with open(parmfile, 'w') as _out:
    for arg in sys.argv[1:]:
        arg = arg.replace("\ ", " ")
        _out.write(arg + "\n")
subprocess.call(['python', '/home/albert/filefindr/afrift_multi.py', parmfile])
