#! /bin/bash

echo check hg_repos on `date` > /tmp/hg_changes
echo '' >> /tmp/hg_changes
set changes = 'No'
#for name in  cobtools jvsdoe leesjcl notetree tcmdrkeys
for name in apropos doctree filefindr htmledit logviewer probreg rst2html-web xmledit
do
    cd ~/hg_repos/$name
    hg status --quiet > /tmp/hg_st_$name
    if [ -s /tmp/hg_st_$name ]
    then
        echo $name: uncommitted changes >> /tmp/hg_changes
        cat /tmp/hg_changes /tmp/hg_st_$name > /tmp/hg_cent
        mv /tmp/hg_cent /tmp/hg_changes
        echo '' >> /tmp/hg_changes
        set changes = 'Yes'
    else
        hg tip > /tmp/${name}_tip
        if cmp -s /tmp/${name}_tip ~/hg_repos/${name}_tip; then
            echo $name: no pending changes >> /tmp/hg_changes
        else
            echo outgoing changes for $name
            echo $name: outgoing changes in `pwd` >> /tmp/hg_changes
            set changes = 'Yes'
        fi
    fi
done

for name in bin nginx-config
do
    cd ~/hg_private/$name
    hg status --quiet > /tmp/hg_st_$name
    if [ -s /tmp/hg_st_$name ]
    then
        echo $name: uncommitted changes >> /tmp/hg_changes
        cat /tmp/hg_changes /tmp/hg_st_$name > /tmp/hg_cent
        mv /tmp/hg_cent /tmp/hg_changes
        echo '' >> /tmp/hg_changes
        set changes = 'Yes'
    else
        hg tip > /tmp/${name}_tip
        if cmp -s /tmp/${name}_tip ~/hg_repos/${name}_tip; then
            echo $name: no pending changes >> /tmp/hg_changes
        else
            echo outgoing changes for $name
            echo $name: outgoing changes in `pwd` >> /tmp/hg_changes
            set changes = 'Yes'
        fi
    fi
done

if [ '$changes' = 'No' ]
then
    echo no local changes
else
    echo for details see /tmp/hg_changes
fi
