#! /bin/bash

echo check usb repos on `date` > /tmp/hg_usb_changes
echo '' >> /tmp/hg_usb_changes
changes='No'
for name in apropos cobtools doctree filefindr htmledit jvsdoe leesjcl notetree probreg rst2html tcmdrkeys xmledit
do
    cd /media/albert/KINGSTON/$name
    hg status --quiet > /tmp/hg_st_$name
    if [ -s /tmp/hg_st_$name ]
    then
        echo '' >> /tmp/hg_st_$name
        echo uncommitted changes for $name
        echo uncommitted changes in `pwd` >> /tmp/hg_usb_changes
        changes='Yes'
        cat /tmp/hg_usb_changes /tmp/hg_st_$name > /tmp/hg_usb
        mv /tmp/hg_usb /tmp/hg_usb_changes
    fi
    inorout='No'
    if hg outgoing > /tmp/hgout; then
        changes='Yes'
        inorout='Yes'
        echo outgoing changes for $name
        echo outgoing changes for $name >> /tmp/hg_usb_changes
        echo --usb out: >> /tmp/hg_usb_changes
    fi
    if hg incoming > /tmp/hgin; then
        changes='Yes'
        inorout='Yes'
        echo incoming changes for $name
        echo incoming changes for $name >> /tmp/hg_usb_changes
        echo --usb in: >> /tmp/hg_usb_changes
    fi
    if [ "$inorout" = "Yes" ]
    then
        hg tip >> /tmp/hg_usb_changes
        cd ~/hg_repos/$name
        echo --hg_repos: >> /tmp/hg_usb_changes
        hg tip >> /tmp/hg_usb_changes
        cd ~/$name
        echo --local: >> /tmp/hg_usb_changes
        hg tip >> /tmp/hg_usb_changes
        echo '' >> /tmp/hg_usb_changes
    fi
done
if [ "$changes" = "No" ]
then
    echo no local changes
else
    echo for details see /tmp/hg_usb_changes
fi
