#! /bin/bash

echo check local repos on `date` > /tmp/hg_local_changes
echo '' >> /tmp/hg_local_changes
changes='No'
for name in apropos cobtools doctree filefindr htmledit jvsdoe leesjcl logviewer notetree probreg rst2html tcmdrkeys xmledit
do
    cd ~/$name
    hg status --quiet > /tmp/hg_st_$name
    if [ -s /tmp/hg_st_$name ]
    then
        echo uncommitted changes for $name
        echo uncommitted changes in `pwd` >> /tmp/hg_local_changes
        changes='Yes'
        cat /tmp/hg_local_changes /tmp/hg_st_$name > /tmp/hg_local
        mv /tmp/hg_local /tmp/hg_local_changes
        echo '' >> /tmp/hg_local_changes
        echo '' >> /tmp/hg_local_changes
    fi
    if hg outgoing > /tmp/hgout; then
        changes='Yes'
        echo outgoing changes for $name
        echo outgoing changes for $name >> /tmp/hg_local_changes
        echo --local: >> /tmp/hg_local_changes
        hg tip >> /tmp/hg_local_changes
        cd ~/hg_repos/$name
        echo --hg_repos: >> /tmp/hg_local_changes
        hg tip >> /tmp/hg_local_changes
        echo '' >> /tmp/hg_local_changes
    else
        echo no outgoing changes for $name
#        echo no outgoing changes for $name >> /tmp/hg_local_changes
    fi
done
for name in bin nginx-config
do
    cd ~/$name
    hg status --quiet > /tmp/hg_st_$name
    if [ -s /tmp/hg_st_$name ]
    then
        echo uncommitted changes for $name
        echo uncommitted changes in `pwd` >> /tmp/hg_local_changes
        changes='Yes'
        cat /tmp/hg_local_changes /tmp/hg_st_$name > /tmp/hg_local
        mv /tmp/hg_local /tmp/hg_local_changes
        echo '' >> /tmp/hg_local_changes
        echo '' >> /tmp/hg_local_changes
    fi
    if hg outgoing > /tmp/hgout; then
        changes='Yes'
        echo outgoing changes for $name
        echo outgoing changes for $name >> /tmp/hg_local_changes
        echo --local: >> /tmp/hg_local_changes
        hg tip >> /tmp/hg_local_changes
        cd ~/hg_private/$name
        echo --hg_private: >> /tmp/hg_local_changes
        hg tip >> /tmp/hg_local_changes
        echo '' >> /tmp/hg_local_changes
    else
        echo no outgoing changes for $name
#        echo no outgoing changes for $name >> /tmp/hg_local_changes
    fi
done
if [ "$changes" = "No" ]
then
    echo no local changes
else
    echo for details see /tmp/hg_local_changes
fi
