#! /bin/sh
files=''
if test "$progs"; then files=$files' '$progs; fi
if test "$dml"; then files=$files' '$dml; fi
if test "$gui"; then files=$files' '$gui; fi
if test "$tpl"; then files=$files' '$tpl; fi
if test "$url"; then files=$files' '$url; fi
if test "$lang"; then files=$files' '$lang; fi
if test "$1"; then
	if [ "$1" = "progs" ] || [ "$1" = "-p" ]; then afrift -P $files &
	else
		if [ "$1" = "tests" ] || [ "$1" = "-t" ]; then afrift -P $tests &
		fi
	fi
else	
	afrift -P $files &
	if test "$tests"; then
       		afrift -P $tests &
	fi
fi
