#! /bin/bash
# kijk of er te synchroniseren wijzigingen zijn (hg outgoing)
# zo ja, sync met central
# uitgangspunt is dat dit een van de door te pushen projecten is
# zo ja, push verder door

cd ~/$1
if hg outgoing; then
    hg push --remotecmd update
    echo $1: pushing to central
fi
if [[ $1 = bin || $1 = nginx-config ]]; then
    cd ../hg_private/$1
else
    cd ../hg_repos/$1
fi
hg push
hg tip > ~/hg_repos/$1_tip
