#! /bin/bash

echo push to bitbucket report on `date` > /tmp/hg_pushbb.log
echo '' >> /tmp/hg_pushbb.log
changes='No'

#for name in  cobtools jvsdoe leesjcl notetree tcmdrkeys
for name in apropos doctree filefindr htmledit logviewer probreg rst2html xmledit
do
    cd ~/hg_repos/$name
    hg status --quiet > /tmp/hg_st_$name
    if [ -s /tmp/hg_st_$name ]
    then
        echo $name not pushed: uncommitted changes >> /tmp/hg_pushbb.log
        changes='Yes'
    else
        hg tip > ~/hg_repos/${name}_newtip
        if cmp -s ~/hg_repos/${name}_newtip ~/hg_repos/${name}_tip; then
            echo $name not pushed: no pending changes >> /tmp/hg_pushbb.log
        else
            hg push
            cp ~/hg_repos/${name}_newtip ~/hg_repos/${name}_tip
            echo $name: pushing to bitbucket >> /tmp/hg_pushbb.log
            changes='Yes'
        fi
        rm ~/hg_repos/${name}_newtip
    fi
done
for name in bin nginx-config
do
    cd ~/hg_private/$name
    hg status --quiet > /tmp/hg_st_$name
    if [ -s /tmp/hg_st_$name ]
    then
        echo $name not pushed: uncommitted changes >> /tmp/hg_pushbb.log
        changes 'Yes'
    else
        hg tip > ~/hg_repos/${name}_newtip
        if cmp -s ~/hg_repos/${name}_newtip ~/hg_repos/${name}_tip; then
            echo $name not pushed: no pending changes >> /tmp/hg_pushbb.log
        else
            hg push
            cp ~/hg_repos/${name}_newtip ~/hg_repos/${name}_tip
            echo $name: pushing to bitbucket >> /tmp/hg_pushbb.log
            changes='Yes'
        fi
        rm ~/hg_repos/${name}_newtip
    fi
done
if [ "$changes" = "No" ]
then
    echo nothing to report
else
    echo for details see /tmp/hg_pushbb.log
fi
