#! /bin/bash

echo push-local report on `date` > /tmp/hg_push.log
echo '' > /tmp/hg_push.log
for name in apropos bin cobtools doctree filefindr htmledit jvsdoe leesjcl logviewer nginx-config notetree probreg rst2html-web tcmdrkeys xmledit
do
    cd ~/$name
    hg status --quiet > /tmp/hg_st_$name
    if [ -s /tmp/hg_st_$name ]
    then
        echo $name not pushed: uncommitted changes >> /tmp/hg_push.log
    else
        if hg outgoing; then
            hg push --remotecmd update
            echo $name: pushing to central >> /tmp/hg_push.log
        fi
    fi
done
