#! /bin/bash

echo push to bitbucket report on `date` > /tmp/hg_local_changes
echo '' >> /tmp/hg_local_changes
set changes = 'No'

#for name in apropos cobtools doctree filefindr htmledit jvsdoe leesjcl logviewer notetree probreg rst2html-web tcmdrkeys xmledit
for name in apropos doctree filefindr htmledit probreg xmledit
do
    cd ~/hg_repos/$name
    hg status --quiet > /tmp/hg_st_$name
    if [ -s /tmp/hg_st_$name ]
    then
        echo $name not pushed: uncommitted changes >> /tmp/hg_push.log
        set changes = 'Yes'
    else
        if hg outgoing > /tmp/hgout; then
            hg push --remotecmd update
            echo $name: pushing to bitbucket >> /tmp/hg_push.log
            set changes = 'Yes'
        fi
    fi
done
for name in bin nginx-config
do
    cd ~/hg_private/$name
    hg status --quiet > /tmp/hg_st_$name
    if [ -s /tmp/hg_st_$name ]
    then
        echo $name not pushed: uncommitted changes >> /tmp/hg_push.log
        set changes = 'Yes'
    else
        if hg outgoing > /tmp/hgout; then
            hg push --remotecmd update
            echo $name: pushing to bitbucket >> /tmp/hg_push.log
            set changes = 'Yes'
        fi
    fi
done
if [ '$changes' = 'No' ]
then
    echo nothing to report
else
    echo for details see /tmp/hg_push.log
fi
